services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
